### ISSUE TITLE
Empty co-authored-by in new repository without warning 

### ISSUE THREAD

**Issue by muan** [koddsson/coworking-with#8]
There should at least be a warning when nothing is found in git log. Perhaps a prompt for people to type for the first entry? Unless there is a smarter way to get author info.

🌷

**Comment by koddsson** [comment]
hello

**Comment by koddsson** [comment]
testing

**Comment by koddsson** [comment]
I'm keeping this open with #9 merged because I think we could maybe do something better than looking up in the git log to create the coauthing line. Maybe we can just fetch fallback to fetching it from the github api or letting the user input it themselves.

**Comment by koddsson** [comment]
https://github.com/koddsson/coworking-with/releases/tag/v0.3.0
